# Generated by Django 2.2.7 on 2019-12-01 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('table_name', models.CharField(max_length=255, unique=True)),
                ('required_fields', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ExecutiveSummaryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('charges', models.DecimalField(decimal_places=2, max_digits=18)),
                ('payments', models.DecimalField(decimal_places=2, max_digits=18)),
                ('adjustments', models.DecimalField(decimal_places=2, max_digits=18)),
                ('date_ran', models.DateField(auto_now_add=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_name', to='app.Reports')),
            ],
        ),
    ]
