# Generated by Django 2.2.7 on 2019-12-03 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191130_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='accountingJE_GLMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('GL', models.CharField(max_length=25)),
            ],
        ),
    ]
